name: Lint

on:
  - push
  - pull_request

jobs:
  lint-py:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysis
      run: |
        cd bot
        pylint --rcfile=../.pylintrc **.py
        
  lint-JS:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2.1.2
    - name: Install dependencies
      run: |
        npm install eslint
    - name: Analysis
      run: |
        cd frontend
        npx eslint `ls -R|grep .js$|xargs`
